const PRODUCTS = [
  {
    _id: '62d9d12150dbc0490ce574af',
    category: 'Leche',
    name: 'Lechota',
    desc: 'La Serenísima. La Leche Clásica Más Liviana Larga Vida tiene un 2% de tenor graso, es U.A.T. homogeneizada, a tu mama le gusta, fortificada con vitaminas A, C, D y E y libre de gluten. Es ideal para quienes buscan (tumadre) tener muchos hijos el equilibrio entre sabor y liviandad.',
    price: 70,
    discount_percentage: 22,
    discount_price_fixed: 22,
    stock: 122,
    __v: 0,
    img: 'https://i.imgur.com/fn3Pwnf.jpg',
  },
  {
    _id: '62e2aba90f08b632d00f2544',
    category: 'Bebidas',
    name: 'CocaCola',
    desc: 'Coca-Cola es una bebida azucarada gaseosa vendida a nivel mundial en tiendas, re cheta la coqueli tu madre la toma con la cola',
    price: 250,
    stock: 350,
    __v: 0,
    img: 'https://i.imgur.com/JkgN02l.jpg',
  },
  {
    _id: '62e2abc80f08b632d00f2545',
    category: 'Pastas',
    name: 'Fideos con tuco',
    desc: 'Son un tipo de pasta con forma alargada. Los fideos pueden ser cortos, como el şehriye o el cabello de ángel, o bien largos y gruesos como los pici o los soba, igualmente largos pero más finos como los spaghetti, o extremadamente finos como los fideos de cristal.',
    price: 420,
    stock: 355,
    __v: 0,
    img: 'https://www.diariamenteali.com/medias/receta-de-fideos-con-pollo-a-la-lombarda-1900Wx500H?context=bWFzdGVyfHJvb3R8MTc3MTg3fGltYWdlL2pwZWd8aDFhL2g0Ny85MDc0MTc1MDQ5NzU4L3JlY2V0YS1kZS1maWRlb3MtY29uLXBvbGxvLWEtbGEtbG9tYmFyZGFfMTkwMFd4NTAwSHw5Mjk5ZjhhNmMwYmM4MzQ2MWU0YWIzNjcwYzE4ZjM2OTNmNGVkYWI2NjllMzY3MjZkYzg2NDE3MmVlNzcwODRj',
  },
  {
    _id: '62e2abf30f08b632d00f2546',
    category: 'Frutas',
    name: 'Manzanas',
    desc: 'La manzana es el fruto comestible tu mama tiene una muy rica de la especie Malus domestica, el manzano común. Es una fruta pomácea de forma redonda y sabor muy dulce, delicioso, dependiendo de la variedad. % de la cantidad diaria recomendada para adultos.',
    price: 500,
    stock: 600,
    __v: 0,
    img: 'https://i.imgur.com/4O5F7ok.jpg',
  },
  {
    _id: '62e35927dbddbc0ba4b89bf7',
    category: 'Pudin',
    desc: 'El budín, pudín o pudin (del inglés pudding) es un tipo de alimento de la cocina inglesa y estadounidense que puede ser un postre o un plato no dulce (salado o picante) que es parte de la comida principal. El postre suele estar compuesto de diferentes ingredientes dependiendo de la región: migas de pan, bizcocho, arroz, sémola, etc',
    price: 55,
    discount_percentage: 22,
    discount_price_fixed: 22,
    stock: 44,
    name: 'Pudin',
    __v: 0,
    img: 'https://i.imgur.com/PZCqwWX.jpg',
  },
];
export default PRODUCTS;
